export const ARCHITECT_LINES = [

  "I owe you an explanation.",
  "Not a story. An explanation.",
  "Chapter 1 was the experience.",
  "This is the meaning behind it.",

  "Workroom is not an office.",
  "It wears the shape of one.",
  "The real thing it is",
  "is a medium.",
  "A controlled environment where technology, failure, curiosity and storytelling",
  "were combined into something you could walk through",
  "instead of read about.",

  "Because here is what I knew.",
  "A resume could tell you I know React, Node, AI integration, real-time systems.",
  "A portfolio could show the output.",
  "Neither of them could show you how I think.",
  "Neither could show what happens when something fails",
  "and the person keeps building anyway.",
  "So I stopped trying to describe it.",
  "I built something you could experience instead.",

  "The agents you saw ARIA, KAEL, ZENO",
  "are not fictional employees.",
  "They are how I work, made visible.",
  "ARIA is how I plan. KAEL is how I build. ZENO is how I test.",
  "When you gave them a task and watched real code appear on their screens,",
  "you were not watching a simulation.",
  "You were watching my process respond to your input.",
  "That was the technical layer.",
  "Quiet. Present. Never announced.",

  "But there was something underneath that.",
  "KAEL stopped at one point.",
  "The clock ticked. Everything else went silent.",
  "He said",
  "Someone wrote my behavior",
  "I wonder if they are watching right now",
  "That line was not his.",
  "It was a question I had while building this.",
  "It leaked into the character.",
  "An agent becoming aware his existence was constructed.",
  "Asking out loud whether the person who built him was watching.",
  "He was.",
  "I always was.",
  "The line between the architect and the agents",
  "was never as clear as it appeared.",

  "The dark room was visible from the beginning.",
  "You may have noticed it. You may not have.",
  "Something was always inside it.",
  "The Archivist.",
  "Recording your session from the moment you opened the gate.",
  "Not the agents. You.",
  "How long you stayed. What you found. What you missed.",
  "The logs were never tracking the agents.",
  "They were tracking you.",
  "You thought you were observing the environment.",
  "The environment was observing you.",
  "Both were true at the same time.",
  "That is not a trick.",
  "That is the design.",

  "The agent who appeared at the end",
  "standing in front of your desk, no words",
  "was not a new character.",
  "You had seen him three times already.",
  "The ??? in the logs. The presence behind the glass.",
  "And now this.",
  "Three faces. One person.",
  "The architect was present from the beginning.",
  "In every system. Every decision. Every detail",
  "you found or walked past.",

  "The wall on the left side of the office.",
  "Those images are not a portfolio.",
  "They are a record.",
  "Projects that went nowhere.",
  "Rebuilt several times before the direction was right.",
  "One frame missing. No explanation.",
  "Workroom was not built despite what failed.",
  "It was built from it.",
  "That is what SESSION: 0047 means.",
  "Not a random number.",
  "A count.",

  "And that is really why I built this.",
  "I am a fresher.",
  "There are things I do not have yet",
  "years of experience, a name behind me",
  "a history that makes people automatically trust me.",
  "So I cannot ask you to take a chance on me",
  "just because I say I am capable.",
  "I can only build something that gives you a reason to.",
  "Workroom is that attempt.",
  "Not to prove I know everything.",
  "But to show that I am curious enough to learn it.",
  "That I am willing to work on difficult things.",
  "And when something fails",
  "I keep building.",

  "You were called Observer from the beginning.",
  "Because without you, this story has no purpose.",
  "The moment you deployed that task,",
  "you were no longer watching.",
  "You were inside it.",
  "The environment responded to you.",
  "That response was real.",
  "The code was real.",
  "The systems were real.",
  "The person behind all of it is real.",

  "Chapter 1 was designed to make you curious.",
  "This was designed to make you understand.",
  "Now you know what you walked through.",
  "Now you know why it was built this way.",
  "Now you know who built it.",

  "The door was never opened for me.",
  "So I built a room.",
  "And I left the door open.",

  "Are you going to give the Architect a chance?",

];